# Generated by Django 4.1.3 on 2023-02-09 07:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aadhaar_no', models.CharField(blank=True, default=0, max_length=12)),
                ('pan_no', models.CharField(blank=True, default=0, max_length=10)),
                ('type_of_employment', models.CharField(blank=True, choices=[('Sal', 'Salaried'), ('SE', 'Self Employeed'), ('B', 'Business')], default=0, max_length=250)),
                ('business_title', models.CharField(blank=True, default=0, max_length=250)),
                ('business_type', models.CharField(blank=True, choices=[('M', 'Manufacture'), ('S', 'Service'), ('T', 'Trading')], default=0, max_length=250)),
                ('business_address', models.TextField(blank=True, default=0)),
                ('gst_registration_no', models.CharField(blank=True, default=0, max_length=50)),
                ('business_license_no', models.CharField(blank=True, default=0, max_length=50)),
                ('expected_average_annual_turnover', models.CharField(blank=True, default=0, max_length=250)),
                ('years_in_current_business', models.IntegerField(blank=True, default=0)),
                ('collateral', models.CharField(blank=True, default=0, max_length=250)),
                ('status', models.CharField(choices=[], default='', max_length=250)),
                ('application_timestamp', models.DateTimeField(auto_now_add=True)),
                ('remark', models.CharField(blank=True, default=0, max_length=250)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Applications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Guarantor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation_with_customer', models.CharField(blank=True, default=0, max_length=250)),
                ('name', models.CharField(blank=True, default=0, max_length=150)),
                ('dob', models.DateField(blank=True, default='2000-12-12')),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default=0, max_length=50)),
                ('email', models.EmailField(blank=True, default=0, max_length=254)),
                ('address', models.TextField(blank=True, default=0, max_length=250)),
                ('city', models.CharField(blank=True, default=0, max_length=50)),
                ('state', models.CharField(blank=True, default=0, max_length=50)),
                ('country', models.CharField(blank=True, default=0, max_length=250)),
                ('pin_code', models.IntegerField(blank=True, default=0)),
                ('mobile', models.CharField(blank=True, default=0, max_length=10)),
                ('photo', models.ImageField(blank=True, default=0, upload_to='media/customer/guarantor/')),
                ('profession', models.CharField(blank=True, default=0, max_length=250)),
                ('income_certificate', models.FileField(blank=True, default=0, upload_to='media/customer/guarantor/')),
                ('bank_name', models.CharField(blank=True, default=0, max_length=250)),
                ('current_account_no', models.CharField(blank=True, default=0, max_length=20)),
                ('passbook_copy', models.FileField(blank=True, default=0, upload_to='media/customer/guarantor/')),
                ('ifsc_code', models.CharField(blank=True, default=0, max_length=20)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Guarantors', to='application_app.application')),
            ],
        ),
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('father_name', models.CharField(blank=True, default=0, max_length=250)),
                ('father_profession', models.CharField(blank=True, default=0, max_length=250)),
                ('mother_name', models.CharField(blank=True, default=0, max_length=250)),
                ('mother_profession', models.CharField(blank=True, default=0, max_length=250)),
                ('marital_status', models.CharField(blank=True, choices=[('M', 'Married'), ('UM', 'Unmarried'), ('D', 'Divorce')], default=0, max_length=250)),
                ('spouse_name', models.CharField(blank=True, default=0, max_length=250)),
                ('spouse_profession', models.CharField(blank=True, default=0, max_length=250)),
                ('mobile', models.CharField(blank=True, default=0, max_length=10)),
                ('address', models.TextField(blank=True, default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Familys', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(blank=True, default=0, max_length=250)),
                ('current_account_no', models.CharField(blank=True, default=0, max_length=20)),
                ('ifsc_code', models.CharField(blank=True, default=0, max_length=20)),
                ('passbook_copy', models.ImageField(blank=True, default=0, upload_to='media/customer/bank/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Banks', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
