# Generated by Django 4.1.3 on 2023-02-09 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_title', models.CharField(blank=True, default=0, max_length=250)),
                ('email', models.EmailField(blank=True, default=0, max_length=254)),
                ('contact_details_1', models.CharField(max_length=15)),
                ('contact_details_2', models.CharField(max_length=15)),
                ('udyog_aadhar_no', models.CharField(blank=True, default=0, max_length=50)),
                ('gst_registration_no', models.CharField(blank=True, default=0, max_length=50)),
                ('business_license_no', models.CharField(blank=True, default=0, max_length=50)),
                ('pan_card_no', models.CharField(blank=True, default=0, max_length=50)),
                ('date_of_incorporation', models.DateField(blank=True)),
                ('business_type', models.CharField(blank=True, choices=[('M', 'Manufacture'), ('S', 'Service'), ('T', 'Trading')], default=0, max_length=250)),
                ('business_constitution', models.CharField(blank=True, choices=[], default='owner', max_length=100)),
                ('business_address', models.TextField(blank=True, default=0)),
                ('CIBIL_score', models.IntegerField(blank=True, default=0)),
                ('past1_year_turnover', models.CharField(blank=True, default=0, max_length=50)),
                ('past2_year_turnover', models.CharField(blank=True, default=0, max_length=50)),
                ('expected_average_annual_turnover', models.CharField(blank=True, default=0, max_length=250)),
                ('years_in_current_business', models.IntegerField(blank=True, default=0)),
                ('loan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Business', to='application_app.application')),
            ],
        ),
    ]
