# Generated by Django 4.1.3 on 2023-02-10 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application_app', '0002_business'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='business_type',
            field=models.CharField(blank=True, choices=[('Sole', 'Sole'), ('Partnership', 'Partnership'), ('Corporation', 'Corporation')], default=0, max_length=250),
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('Inprocess', 'Inprocess'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='application',
            name='type_of_employment',
            field=models.CharField(blank=True, choices=[('Self_employed', 'Self_employed'), ('Private', 'Private')], default=0, max_length=250),
        ),
        migrations.AlterField(
            model_name='business',
            name='business_constitution',
            field=models.CharField(blank=True, choices=[('Private_limited', 'Private_limited'), ('Public_limited', 'Public_limited'), ('Partnership', 'Partnership'), ('One_person_companies', 'One_person_companies')], default='owner', max_length=100),
        ),
        migrations.AlterField(
            model_name='business',
            name='business_type',
            field=models.CharField(blank=True, choices=[('Sole', 'Sole'), ('Partnership', 'Partnership'), ('Corporation', 'Corporation')], default=0, max_length=250),
        ),
        migrations.AlterField(
            model_name='family',
            name='marital_status',
            field=models.CharField(blank=True, choices=[('Married', 'Married'), ('Unmarried', 'Unmarried'), ('Divorse', 'Divorse')], default=0, max_length=250),
        ),
        migrations.AlterField(
            model_name='guarantor',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default=0, max_length=50),
        ),
        migrations.DeleteModel(
            name='Bank',
        ),
    ]
