# Generated by Django 4.1.3 on 2023-02-10 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan_sanctioning', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='status',
            field=models.CharField(blank=True, choices=[('Late', 'Late'), ('Overdue', 'Overdue'), ('Default', 'Default')], default=0, max_length=250),
        ),
    ]
