# Generated by Django 4.1.3 on 2023-02-09 07:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('application_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aadhaar_card', models.FileField(blank=True, default=0, upload_to='customer/document/')),
                ('pan_card', models.FileField(blank=True, default=0, upload_to='customer/document/')),
                ('business_address_proof_or_copy_of_rent_agreement', models.FileField(blank=True, default=0, upload_to='customer/document/')),
                ('electricity_bill', models.FileField(blank=True, default=0, upload_to='customer/document/')),
                ('msme_certificate', models.FileField(blank=True, default=0, upload_to='customer/document/')),
                ('gst_certificate', models.FileField(blank=True, default=0, upload_to='customer/document/')),
                ('udyog_aadhaar_registration', models.FileField(blank=True, default=0, upload_to='customer/document/')),
                ('business_license', models.FileField(blank=True, default=0, upload_to='customer/document/')),
                ('business_plan_or_proposal', models.FileField(blank=True, default=0, upload_to='customer/document/')),
                ('three_year_itr_with_balance_sheet', models.FileField(blank=True, default=0, upload_to='customer/document/')),
                ('collateral_document', models.FileField(blank=True, default=0, upload_to='customer/document/')),
                ('stamp_duty', models.FileField(blank=True, default=0, upload_to='customer/document/')),
                ('status', models.CharField(blank=True, choices=[], default=0, max_length=250)),
                ('response_timestamp', models.DateTimeField(auto_now=True)),
                ('remark', models.CharField(blank=True, default=0, max_length=250)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Documents', to='application_app.application')),
            ],
        ),
    ]
